# Generated by Django 5.2.17 on 2026-08-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessment', '0001_initial'),
        ('core', '0001_initial'),
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examregistration',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_registrations', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='examattempt',
            name='registration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessment.examregistration'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='assessment.exam'),
        ),
        migrations.AddField(
            model_name='examsection',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.examsection'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='assessment.exam'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='organization.room'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='examregistration',
            name='exam_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='assessment.examsession'),
        ),
        migrations.AddField(
            model_name='gradeappeal',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to='assessment.examattempt'),
        ),
        migrations.AddField(
            model_name='gradeappeal',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='gradereview',
            name='attempt_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='assessment.attemptanswer'),
        ),
        migrations.AddField(
            model_name='gradereview',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='proctorevent',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_events', to='assessment.examattempt'),
        ),
        migrations.AddField(
            model_name='proctorevent',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='question',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_banks', to='organization.course'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='organization.school'),
        ),
        migrations.AddField(
            model_name='questionbank',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='question',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.questionbank'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_tags', to='organization.school'),
        ),
        migrations.AddField(
            model_name='questiontag',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='version_links', to='assessment.questiontag'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_versions', to='organization.gradelevel'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessment.question'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='tags',
            field=models.ManyToManyField(related_name='question_versions', through='assessment.QuestionTagLink', to='assessment.questiontag'),
        ),
        migrations.AddField(
            model_name='questionversion',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='questiontaglink',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='assessment.questionversion'),
        ),
        migrations.AddField(
            model_name='questionoption',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assessment.questionversion'),
        ),
        migrations.AddField(
            model_name='question',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_of', to='assessment.questionversion'),
        ),
        migrations.AddField(
            model_name='examquestion',
            name='question_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_questions', to='assessment.questionversion'),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='uq_exam_tenant_code'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'grading_status'], name='assessment__attempt_eaf8ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'exam_question'), name='uq_attempt_answer'),
        ),
        migrations.AddIndex(
            model_name='examattempt',
            index=models.Index(fields=['status', 'expires_at'], name='assessment__status_0098f2_idx'),
        ),
        migrations.AddConstraint(
            model_name='examattempt',
            constraint=models.UniqueConstraint(fields=('registration', 'attempt_no'), name='uq_attempt_registration_no'),
        ),
        migrations.AddConstraint(
            model_name='examsession',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='ck_exam_session_window'),
        ),
        migrations.AddConstraint(
            model_name='examregistration',
            constraint=models.UniqueConstraint(fields=('exam_session', 'enrollment'), name='uq_exam_registration'),
        ),
        migrations.AddConstraint(
            model_name='questiontag',
            constraint=models.UniqueConstraint(fields=('school', 'tag_type', 'value'), name='uq_question_tag'),
        ),
        migrations.AddConstraint(
            model_name='questionversion',
            constraint=models.UniqueConstraint(fields=('question', 'version_no'), name='uq_question_version_no'),
        ),
        migrations.AddConstraint(
            model_name='questiontaglink',
            constraint=models.UniqueConstraint(fields=('question_version', 'tag'), name='uq_question_tag_link'),
        ),
        migrations.AddConstraint(
            model_name='questionoption',
            constraint=models.UniqueConstraint(fields=('question_version', 'option_key'), name='uq_option_key'),
        ),
        migrations.AddConstraint(
            model_name='examquestion',
            constraint=models.UniqueConstraint(fields=('section', 'question_version'), name='uq_exam_section_question'),
        ),
    ]
