# Generated by Django 5.2.17 on 2026-08-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('finance', '0001_initial'),
        ('identity', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='identity.person'),
        ),
        migrations.AddField(
            model_name='payment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.invoice'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='paymentallocation',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='refund',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='refund',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='studentfinancialagreement',
            name='enrollment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='financial_agreement', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='studentfinancialagreement',
            name='fee_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agreements', to='finance.feeplan'),
        ),
        migrations.AddField(
            model_name='studentfinancialagreement',
            name='responsible_guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='financial_agreements', to='students.guardian', verbose_name='مسئول مالی'),
        ),
        migrations.AddField(
            model_name='studentfinancialagreement',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='finance.studentfinancialagreement'),
        ),
        migrations.AddField(
            model_name='discountaward',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='finance.studentfinancialagreement'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uq_account_school_code'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='uq_cost_center_school_code'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.UniqueConstraint(fields=('school', 'title'), name='uq_fiscal_year_school_title'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['source_type', 'source_id'], name='finance_jou_source__2c7396_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(fields=('tenant', 'entry_no'), name='uq_journal_tenant_no'),
        ),
        migrations.AddIndex(
            model_name='journalline',
            index=models.Index(fields=['account', 'journal_entry'], name='finance_jou_account_3cdb75_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), _connector='OR'), name='ck_journal_line_debit_xor_credit'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('tenant', 'payment_no'), name='uq_payment_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('tenant', 'idempotency_key'), name='uq_payment_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentallocation',
            constraint=models.UniqueConstraint(fields=('payment', 'invoice'), name='uq_payment_invoice_allocation'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(fields=('tenant', 'refund_no'), name='uq_refund_tenant_no'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['agreement', 'status'], name='finance_inv_agreeme_973890_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='finance_inv_due_dat_fb9ca1_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('tenant', 'invoice_no'), name='uq_invoice_tenant_no'),
        ),
    ]
