# Generated by Django 5.2.17 on 2026-08-26 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='school',
            field=models.ForeignKey(blank=True, help_text='برای تعیین کدینگ حساب و سال مالی هنگام ثبت سند', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='organization.school', verbose_name='مدرسه'),
        ),
    ]
