# Generated by Django 5.2.17 on 2026-09-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='token_version',
            field=models.PositiveIntegerField(default=1, help_text='بخش ۱۵.۱: «تغییر رمز یا نقش حساس، Sessionهای پرریسک را باطل می\u200cکند». این عدد در هر توکن صادرشده می\u200cنشیند و لایه احراز هویت توکنی را که نسخه\u200cاش کهنه است رد می\u200cکند. یک واحد افزایش = ابطال فوری همه توکن\u200cهای در گردش این کاربر.', verbose_name='نسخه توکن'),
        ),
    ]
