# Generated by Django 5.2.17 on 2026-08-26 09:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ایجاد')),
                ('created_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='ایجادکننده')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('updated_by_id', models.UUIDField(blank=True, editable=False, null=True, verbose_name='ویرایش\u200cکننده')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='نسخه رکورد')),
                ('name', models.CharField(max_length=200, verbose_name='نام سازمان')),
                ('code', models.SlugField(max_length=60, unique=True, verbose_name='کد یکتا')),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال'), ('ARCHIVED', 'بایگانی\u200cشده')], default='ACTIVE', max_length=20)),
                ('default_currency', models.CharField(default='IRR', max_length=3, verbose_name='واحد پول پیش\u200cفرض')),
                ('default_timezone', models.CharField(default='Asia/Tehran', max_length=64)),
            ],
            options={
                'verbose_name': 'سازمان',
                'verbose_name_plural': 'سازمان\u200cها',
                'ordering': ('name',),
            },
        ),
    ]
