# Generated by Django 5.2.17 on 2026-08-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('hr', '0001_initial'),
        ('identity', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='employee_profile', to='identity.person'),
        ),
        migrations.AddField(
            model_name='employee',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_assignments', to='organization.campus'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='employmentcontract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substitute_for_leaves', to='hr.employee', verbose_name='جانشین'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_units', to='organization.campus'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hr.orgunit'),
        ),
        migrations.AddField(
            model_name='orgunit',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_runs', to='organization.school'),
        ),
        migrations.AddField(
            model_name='payrollrun',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='correction_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corrections', to='hr.payslip', verbose_name='فیش مابه\u200cالتفاوت برای'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='payroll_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payslips', to='hr.payrollrun'),
        ),
        migrations.AddField(
            model_name='payslip',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='payslip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hr.payslip'),
        ),
        migrations.AddField(
            model_name='payslipitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='position',
            name='org_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='hr.orgunit'),
        ),
        migrations.AddField(
            model_name='position',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='hr.position'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to='hr.employee'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='teacherqualification',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualified_teachers', to='organization.course'),
        ),
        migrations.AddField(
            model_name='teacherqualification',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_qualifications', to='organization.gradelevel'),
        ),
        migrations.AddField(
            model_name='teacherqualification',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='hr.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teacherqualification',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='course_offering',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to='organization.courseoffering'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='teacher_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teaching_assignments', to='hr.teacherprofile'),
        ),
        migrations.AddField(
            model_name='teachingassignment',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='organization.campus'),
        ),
        migrations.AddField(
            model_name='workshift',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='hr.workshift'),
        ),
        migrations.AddConstraint(
            model_name='employee',
            constraint=models.UniqueConstraint(fields=('tenant', 'employee_no'), name='uq_employee_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='employmentcontract',
            constraint=models.UniqueConstraint(fields=('tenant', 'contract_no'), name='uq_contract_tenant_no'),
        ),
        migrations.AddConstraint(
            model_name='leaverequest',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='ck_leave_end_after_start'),
        ),
        migrations.AddConstraint(
            model_name='orgunit',
            constraint=models.UniqueConstraint(fields=('campus', 'code'), name='uq_orgunit_campus_code'),
        ),
        migrations.AddConstraint(
            model_name='payslip',
            constraint=models.UniqueConstraint(condition=models.Q(('correction_of__isnull', True)), fields=('payroll_run', 'employee'), name='uq_payslip_run_employee'),
        ),
        migrations.AddConstraint(
            model_name='position',
            constraint=models.UniqueConstraint(fields=('org_unit', 'code'), name='uq_position_unit_code'),
        ),
        migrations.AddIndex(
            model_name='employeeassignment',
            index=models.Index(fields=['employee', 'effective_from'], name='hr_employee_employe_906712_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherqualification',
            constraint=models.UniqueConstraint(fields=('teacher_profile', 'course', 'grade_level'), name='uq_teacher_course_grade'),
        ),
        migrations.AddIndex(
            model_name='teachingassignment',
            index=models.Index(fields=['course_offering', 'teacher_profile'], name='hr_teaching_course__72f0de_idx'),
        ),
        migrations.AddConstraint(
            model_name='employeeattendance',
            constraint=models.UniqueConstraint(fields=('employee', 'work_date'), name='uq_employee_attendance_date'),
        ),
    ]
