"""
واژه‌نامه برچسب فارسی فیلدهای مدل.

**مسئله.** از ۲۵۹۳ فیلد سامانه، ۱۰۴۴ فیلد `verbose_name` صریح ندارند. جنگو در
نبود آن، نام فیلد را با فاصله برمی‌گرداند؛ نتیجه‌اش سرستون «material type» در
پنل مدیریت و `title: "source type"` در قرارداد OpenAPI است.

**چرا اینجا و نه در `models.py`.** همان نام‌ها ده‌ها بار در ماژول‌های مختلف
تکرار می‌شوند — `status` در ۷۳ مدل، `deleted_by_id` در ۱۳۴ مدل. نوشتن برچسب
کنار تک‌تک تعریف‌ها یعنی هزار سطر تکرار که با هر مدل تازه دوباره از قلم می‌افتد.
واژه‌نامه متمرکز یک‌بار نوشته می‌شود و هر سه مصرف‌کننده را هم‌زمان درست می‌کند:

- سرستون، فیلتر و برچسب فرم در پنل مدیریت
- `label` فیلدهای سریالایزر در Django REST Framework
- `title` مشخصه‌ها در قرارداد OpenAPI

**اولویت.** فیلدی که در `models.py` برچسب فارسی صریح دارد دست نمی‌خورد؛ این
واژه‌نامه فقط جای خالی را پر می‌کند.
"""

from __future__ import annotations

import re

from django.apps import apps as django_apps
from django.db import models

#: تشخیص برچسبی که واقعاً فارسی نوشته شده است.
_PERSIAN = re.compile(r"[؀-ۿ]")

#: نگاشت نام فیلد به برچسب فارسی.
#:
#: کلیدها نام فیلد در مدل‌اند، نه نام ستون پایگاه داده. ترتیب گروه‌ها موضوعی
#: است تا افزودن واژه تازه ساده بماند.
FIELD_LABELS: dict[str, str] = {
    # --- مشترک بین ماژول‌ها ---------------------------------------------
    "status": "وضعیت",
    "title": "عنوان",
    "description": "شرح",
    "note": "یادداشت",
    "notes": "یادداشت‌ها",
    "code": "کد",
    "reason": "علت",
    "is_active": "فعال",
    "tenant": "سازمان",
    "currency": "واحد پول",
    "amount": "مبلغ",
    "quantity": "تعداد",
    "display_order": "ترتیب نمایش",
    "version_no": "شماره نسخه",
    "location": "محل",
    "priority": "اولویت",
    "severity": "شدت",
    "direction": "جهت",
    "source": "منبع",
    "source_type": "نوع منبع",
    "source_id": "شناسه منبع",
    "category": "دسته",
    "content": "محتوا",
    "body": "متن",
    "subject": "موضوع",
    "comment": "توضیح",
    "value": "مقدار",
    "details": "جزئیات",
    "result": "نتیجه",
    "purpose": "هدف",
    "parent": "والد",
    "applied": "اعمال‌شده",
    "difference": "اختلاف",
    "method": "روش",
    "mode": "حالت",
    "channel": "کانال",
    "template": "قالب",
    "recurrence": "تکرار",
    "instructions": "دستورالعمل",
    "feedback": "بازخورد",
    "resolution": "نتیجه رسیدگی",
    "outcome": "نتیجه",
    "action": "عمل",
    "visibility": "سطح نمایش",
    "classification": "طبقه‌بندی",
    "confidentiality_level": "سطح محرمانگی",
    "deleted_by_id": "حذف‌کننده",
    # --- فایل، رسانه و ارتباطات ------------------------------------------
    "file": "فایل",
    "media": "رسانه",
    "attachment": "پیوست",
    "logo": "نشان",
    "barcode": "بارکد",
    "url": "نشانی اینترنتی",
    "phone": "تلفن",
    "email": "رایانامه",
    "address": "نشانی",
    "address_line": "سطر نشانی",
    "country": "کشور",
    "language": "زبان",
    "locale": "زبان و منطقه",
    "preferred_locale": "زبان ترجیحی",
    "timezone": "منطقه زمانی",
    "default_timezone": "منطقه زمانی پیش‌فرض",
    "latitude": "عرض جغرافیایی",
    "longitude": "طول جغرافیایی",
    "media_type": "نوع محتوا",
    "original_name": "نام اصلی فایل",
    "size_bytes": "حجم (بایت)",
    "sha256": "چکیده SHA-256",
    "scan_status": "وضعیت پویش بدافزار",
    "provider": "ارائه‌دهنده",
    "provider_reference": "ارجاع ارائه‌دهنده",
    "subject_template": "قالب موضوع",
    # --- زمان و تاریخ -----------------------------------------------------
    "occurred_at": "زمان رخداد",
    "decided_at": "زمان تصمیم",
    "approved_at": "زمان تأیید",
    "published_at": "زمان انتشار",
    "closed_at": "زمان بستن",
    "reviewed_at": "زمان بازبینی",
    "completed_at": "زمان تکمیل",
    "submitted_at": "زمان ارسال",
    "verified_at": "زمان تأیید هویت",
    "revoked_at": "زمان ابطال",
    "opened_at": "زمان بازکردن",
    "expires_at": "زمان انقضا",
    "changed_at": "زمان تغییر",
    "calculated_at": "زمان محاسبه",
    "resolved_at": "زمان رسیدگی",
    "returned_at": "زمان بازگشت",
    "granted_at": "زمان اعطا",
    "executed_at": "زمان اجرا",
    "started_at": "زمان شروع",
    "saved_at": "زمان ذخیره",
    "last_saved_at": "زمان آخرین ذخیره",
    "locked_at": "زمان قفل",
    "recorded_at": "زمان ثبت",
    "generated_at": "زمان تولید",
    "posted_at": "زمان قطعی‌سازی",
    "allocated_at": "زمان تخصیص",
    "confirmed_at": "زمان تأیید سند",
    "reconciled_at": "زمان تطبیق",
    "received_at": "زمان دریافت",
    "assigned_at": "زمان تخصیص",
    "held_at": "زمان برگزاری",
    "next_followup_at": "زمان پیگیری بعدی",
    "loaned_at": "زمان امانت",
    "departed_at": "زمان حرکت",
    "requested_at": "زمان درخواست",
    "scheduled_at": "زمان زمان‌بندی‌شده",
    "sent_at": "زمان ارسال",
    "read_at": "زمان خواندن",
    "attempted_at": "زمان تلاش",
    "scanned_at": "زمان پویش",
    "received_or_sent_at": "زمان دریافت یا ارسال",
    "attendance_finalized_at": "زمان قطعی‌شدن حضور",
    "password_changed_at": "زمان تغییر گذرواژه",
    "last_login_at": "آخرین ورود",
    "date_joined": "تاریخ عضویت",
    "locked_until": "قفل تا",
    "guardian_notified_at": "زمان اطلاع به ولی",
    "results_published_at": "زمان انتشار نتایج",
    "appeal_deadline": "مهلت اعتراض",
    "check_in_at": "زمان ورود",
    "check_out_at": "زمان خروج",
    "due_at": "مهلت",
    "starts_at": "زمان شروع",
    "ends_at": "زمان پایان",
    "starts_on": "تاریخ شروع",
    "ends_on": "تاریخ پایان",
    "issued_on": "تاریخ صدور",
    "due_on": "سررسید",
    "valid_until": "معتبر تا",
    "work_date": "تاریخ کاری",
    "entry_date": "تاریخ سند",
    "period_start": "آغاز دوره",
    "period_end": "پایان دوره",
    "period_from": "از دوره",
    "period_to": "تا دوره",
    "effective_from": "معتبر از",
    "effective_until": "معتبر تا",
    "opened_on": "تاریخ گشایش",
    "closed_on": "تاریخ بستن",
    "acquired_on": "تاریخ تملک",
    "ordered_on": "تاریخ سفارش",
    "expected_on": "تاریخ مورد انتظار",
    "needed_by": "نیاز تا تاریخ",
    "expiry_date": "تاریخ انقضا",
    "cheque_due_date": "تاریخ سررسید چک",
    "warranty_until": "گارانتی تا",
    "insurance_valid_until": "اعتبار بیمه تا",
    "run_date": "تاریخ سرویس",
    "scheduled_time": "ساعت برنامه",
    "publish_year": "سال انتشار",
    "planned_for": "برنامه‌ریزی‌شده برای",
    "quiet_hours_start": "آغاز ساعات سکوت",
    "quiet_hours_end": "پایان ساعات سکوت",
    # --- عامل عملیات ------------------------------------------------------
    "approved_by_id": "تأییدکننده",
    "decided_by_id": "تصمیم‌گیرنده",
    "reviewed_by_id": "بازبین",
    "closed_by_id": "بستن‌کننده",
    "changed_by_id": "تغییردهنده",
    "recorded_by_id": "ثبت‌کننده",
    "requested_by_id": "درخواست‌دهنده",
    "reported_by_id": "گزارش‌دهنده",
    "granted_by_id": "اعطاکننده",
    "reviewer_id": "شناسه بازبین",
    "actor_user_id": "کاربر عامل",
    "actor_username": "نام کاربری عامل",
    "verified_by_id": "تأییدکننده هویت",
    "submitted_by_id": "ارسال‌کننده",
    "submitted_by_guardian_id": "ولی ارسال‌کننده",
    "resolved_by_id": "رسیدگی‌کننده",
    "locked_by_id": "قفل‌کننده",
    "published_by_id": "منتشرکننده",
    "posted_by_id": "قطعی‌کننده سند",
    "confirmed_by_id": "تأییدکننده سند",
    "reconciled_by_id": "تطبیق‌دهنده",
    "assigned_by_id": "تخصیص‌دهنده",
    "cashier_user_id": "صندوق‌دار",
    "requester_user_id": "کاربر درخواست‌دهنده",
    "assignee_user_id": "کاربر مسئول",
    "author_user_id": "کاربر نویسنده",
    "approver_user_id": "کاربر تأییدکننده",
    "proctor_employee_id": "مراقب آزمون",
    "counselor_employee_id": "مشاور",
    "keeper_employee_id": "انباردار",
    "driver_employee_id": "راننده",
    "supervisor_employee_id": "سرپرست",
    "default_driver_employee_id": "راننده پیش‌فرض",
    "expense_account_id": "حساب هزینه",
    "cost_center_id": "مرکز هزینه",
    # --- روابط سازمانی و آموزشی -------------------------------------------
    "school": "مدرسه",
    "campus": "شعبه",
    "student": "دانش‌آموز",
    "person": "شخص",
    "enrollment": "ثبت‌نام",
    "course_offering": "ارائه درس",
    "course": "درس",
    "academic_year": "سال تحصیلی",
    "grade_level": "پایه تحصیلی",
    "program": "رشته",
    "class_group": "کلاس",
    "term": "ترم",
    "room": "اتاق",
    "employee": "کارمند",
    "teacher_profile": "پرونده معلم",
    "guardian": "ولی",
    "session": "جلسه",
    "schedule_entry": "سطر برنامه هفتگی",
    "org_unit": "واحد سازمانی",
    "position": "سِمت",
    "shift": "شیفت",
    "duty": "وظیفه",
    "admission_application": "درخواست پذیرش",
    "preferred_campus": "شعبه ترجیحی",
    "preferred_grade_level": "پایه ترجیحی",
    "preferred_program": "رشته ترجیحی",
    "current_room": "اتاق فعلی",
    "room_type": "نوع اتاق",
    "weekly_minutes": "دقیقه در هفته",
    "specialization": "تخصص",
    "responsibility": "مسئولیت",
    # --- تکلیف، آزمون و نمره ----------------------------------------------
    "assignment": "تکلیف",
    "submission": "تحویل",
    "attendance": "حضور و غیاب",
    "exam": "آزمون",
    "exam_session": "جلسه آزمون",
    "exam_question": "سؤال آزمون",
    "question": "سؤال",
    "question_version": "نسخه سؤال",
    "current_version": "نسخه جاری",
    "attempt": "تلاش",
    "attempt_answer": "پاسخ تلاش",
    "registration": "ثبت‌نام آزمون",
    "section": "بخش",
    "bank": "بانک سؤال",
    "tag": "برچسب",
    "tags": "برچسب‌ها",
    "review": "بازبینی",
    "grade_item": "قلم نمره",
    "student_score": "نمره دانش‌آموز",
    "report_card": "کارنامه",
    "course_result": "نتیجه درس",
    "score": "نمره",
    "awarded_score": "نمره اعطاشده",
    "auto_score": "نمره خودکار",
    "manual_score": "نمره دستی",
    "final_score": "نمره نهایی",
    "displayed_score": "نمره نمایشی",
    "displayed_level": "سطح نمایشی",
    "letter_grade": "نمره حرفی",
    "qualitative_level": "سطح کیفی",
    "old_score": "نمره پیشین",
    "new_score": "نمره جدید",
    "score_before": "نمره پیش از تغییر",
    "score_after": "نمره پس از تغییر",
    "difficulty": "دشواری",
    "is_correct": "پاسخ درست",
    "is_required": "الزامی",
    "is_mandatory": "اجباری",
    "is_final": "نهایی",
    "is_late": "با تأخیر",
    "show_result_immediately": "نمایش فوری نتیجه",
    "time_limit_minutes": "محدودیت زمان (دقیقه)",
    "time_spent_seconds": "زمان صرف‌شده (ثانیه)",
    "duration_minutes": "مدت (دقیقه)",
    "attempt_limit": "سقف تلاش",
    "max_attempts": "حداکثر تلاش",
    "attempt_no": "شماره تلاش",
    "seat_no": "شماره صندلی",
    "drop_policy": "سیاست حذف",
    "evidence_file": "فایل مستند",
    "evidence_ref": "ارجاع مستند",
    "attendance_summary": "خلاصه حضور",
    "attendees": "حاضران",
    "calculation_version": "نسخه محاسبه",
    "save_revision": "شماره بازنگری ذخیره",
    "principal_comment": "نظر مدیر",
    "teacher_comment": "نظر معلم",
    "late_minutes": "دقیقه تأخیر",
    "early_leave_minutes": "دقیقه خروج زودهنگام",
    "worked_minutes": "دقیقه کارکرد",
    "overtime_minutes": "دقیقه اضافه‌کاری",
    "requested_minutes": "دقیقه درخواستی",
    # --- مالی --------------------------------------------------------------
    "invoice": "صورتحساب",
    "payment": "پرداخت",
    "agreement": "توافق‌نامه",
    "fee_plan": "طرح شهریه",
    "fee_type": "نوع شهریه",
    "bank_account": "حساب بانکی",
    "bank_name": "نام بانک",
    "account": "حساب",
    "ledger_account": "حساب دفتر کل",
    "revenue_account": "حساب درآمد",
    "journal_entry": "سند حسابداری",
    "fiscal_year": "سال مالی",
    "cost_center": "مرکز هزینه",
    "payroll_run": "دوره حقوق",
    "payslip": "فیش حقوقی",
    "payer_person": "پرداخت‌کننده",
    "credit": "بستانکار",
    "unit_amount": "مبلغ واحد",
    "net_amount": "مبلغ خالص",
    "total_amount": "مبلغ کل",
    "tax_amount": "مبلغ مالیات",
    "discount_amount": "مبلغ تخفیف",
    "discount_type": "نوع تخفیف",
    "cost_amount": "مبلغ هزینه",
    "estimated_amount": "مبلغ برآوردی",
    "budget_reserved_amount": "بودجه رزروشده",
    "vendor_invoice_amount": "مبلغ فاکتور تأمین‌کننده",
    "acquisition_cost": "بهای تملک",
    "unit_cost": "بهای واحد",
    "unit_price": "قیمت واحد",
    "estimated_unit_price": "قیمت واحد برآوردی",
    "accumulated_depreciation": "استهلاک انباشته",
    "monthly_fee": "هزینه ماهانه",
    "gateway_reference": "ارجاع درگاه پرداخت",
    "idempotency_key": "کلید یکتایی درخواست",
    "installment_count": "تعداد اقساط",
    "decimal_places": "تعداد رقم اعشار",
    "fine_paid": "جریمه پرداخت‌شده",
    # --- خرید، انبار و اموال ----------------------------------------------
    "item": "کالا",
    "item_type": "نوع قلم",
    "warehouse": "انبار",
    "vendor": "تأمین‌کننده",
    "uom": "واحد سنجش",
    "base_uom": "واحد سنجش پایه",
    "stock_document": "سند انبار",
    "document_line": "سطر سند",
    "document_type": "نوع سند",
    "purchase_request": "درخواست خرید",
    "request": "درخواست",
    "order": "سفارش",
    "asset": "دارایی",
    "batch": "دسته",
    "reversal_of": "برگشت سند",
    "signed_quantity": "مقدار علامت‌دار",
    "ordered_qty": "مقدار سفارش",
    "received_qty": "مقدار دریافت",
    "min_stock": "حداقل موجودی",
    "max_stock": "حداکثر موجودی",
    "lot_no": "شماره بچ",
    "useful_life_months": "عمر مفید (ماه)",
    "condition_status": "وضعیت فنی",
    "condition_on_assign": "وضعیت هنگام تحویل",
    "condition_on_return": "وضعیت هنگام بازگشت",
    "location_room": "اتاق محل استقرار",
    "contact_person": "شخص رابط",
    "quality_status": "وضعیت کیفی",
    "maintenance_type": "نوع نگهداشت",
    "justification": "توجیه",
    "insurance_policy_no": "شماره بیمه‌نامه",
    "model_name": "نام مدل",
    # --- سلامت، مشاوره و انضباط -------------------------------------------
    "health_profile": "پرونده سلامت",
    "case": "پرونده",
    "incident": "رخداد",
    "incident_type": "نوع رخداد",
    "alert_type": "نوع هشدار",
    "action_taken": "اقدام انجام‌شده",
    "action_type": "نوع عمل",
    "investigation_note": "توضیح بررسی",
    "referral_source": "منبع ارجاع",
    "blood_type": "گروه خونی",
    "height_cm": "قد (سانتی‌متر)",
    "weight_kg": "وزن (کیلوگرم)",
    "emergency_contact": "تماس اضطراری",
    "emergency_contact_name": "نام تماس اضطراری",
    "emergency_contact_phone": "تلفن تماس اضطراری",
    "family_physician": "پزشک خانواده",
    "insurance_no": "شماره بیمه",
    # --- کتابخانه و حمل‌ونقل ----------------------------------------------
    "isbn": "شابک",
    "author": "نویسنده",
    "publisher": "ناشر",
    "material_type": "نوع ماده",
    "title_ref": "عنوان کتاب",
    "copy": "نسخه",
    "borrower_person": "امانت‌گیرنده",
    "renewal_count": "تعداد تمدید",
    "vehicle": "خودرو",
    "default_vehicle": "خودرو پیش‌فرض",
    "route": "مسیر",
    "route_run": "سرویس مسیر",
    "stop": "ایستگاه",
    "pickup_stop": "ایستگاه سوارشدن",
    "dropoff_stop": "ایستگاه پیاده‌شدن",
    # --- گردش کار، اعلان و یکپارچه‌سازی ------------------------------------
    "notification": "اعلان",
    "ticket": "تیکت",
    "recipient_person": "گیرنده",
    "requester_person": "درخواست‌دهنده",
    "workflow_code": "کد گردش کار",
    "workflow_version": "نسخه گردش کار",
    "integration_code": "کد یکپارچه‌سازی",
    "external_message_id": "شناسه پیام بیرونی",
    "approver_type": "نوع تأییدکننده",
    "approver_role_code": "کد نقش تأییدکننده",
    "assignee_type": "نوع تحویل‌گیرنده",
    "assignee_id": "شناسه تحویل‌گیرنده",
    "owner_type": "نوع مالک",
    "owner_id": "شناسه مالک",
    "related_type": "نوع مرتبط",
    "related_id": "شناسه مرتبط",
    "subject_type": "نوع موضوع",
    "subject_id": "شناسه موضوع",
    "subject_label": "عنوان موضوع",
    "aggregate_type": "نوع تجمیع",
    "aggregate_id": "شناسه تجمیع",
    "schema_version": "نسخه قرارداد",
    "payload": "بار داده",
    "payload_digest": "چکیده بار داده",
    "correlation_id": "شناسه ردیابی",
    "causation_id": "شناسه رویداد مسبب",
    "error_message": "پیام خطا",
    "last_error": "آخرین خطا",
    "retry_count": "تعداد تلاش مجدد",
    "sequence_no": "شماره ترتیب",
    "allow_sms": "اجازه پیامک",
    "allow_email": "اجازه رایانامه",
    "allow_push": "اجازه اعلان Push",
    "allow_promotional": "اجازه پیام تبلیغاتی",
    # --- هویت و دسترسی ------------------------------------------------------
    "user": "کاربر",
    "role": "نقش",
    "permission": "مجوز",
    "permissions": "مجوزها",
    "grant_reason": "علت اعطا",
    "scope_note": "توضیح دامنه",
    "mfa_method": "روش احراز چندعاملی",
    "must_change_password": "الزام تغییر گذرواژه",
    "failed_login_count": "تعداد ورود ناموفق",
    "last_login_ip": "نشانی IP آخرین ورود",
    "client_ip": "نشانی IP کلاینت",
    "user_agent": "عامل کاربر",
    "entity_type": "نوع موجودیت",
    "entity_id": "شناسه موجودیت",
    "entity_label": "عنوان موجودیت",
    "address_type": "نوع نشانی",
    "verification_status": "وضعیت تأیید",
    # --- وضعیت و نوع --------------------------------------------------------
    "approval_status": "وضعیت تأیید",
    "attendance_status": "وضعیت حضور",
    "finalization_status": "وضعیت قطعی‌سازی",
    "lifecycle_status": "وضعیت چرخه عمر",
    "registration_status": "وضعیت ثبت‌نام",
    "qualification_status": "وضعیت صلاحیت",
    "result_status": "وضعیت نتیجه",
    "grading_status": "وضعیت تصحیح",
    "review_status": "وضعیت بازبینی",
    "review_type": "نوع بازبینی",
    "account_type": "نوع حساب",
    "contract_type": "نوع قرارداد",
    "position_type": "نوع سِمت",
    "transfer_type": "نوع انتقال",
    "session_type": "نوع جلسه",
    "question_type": "نوع سؤال",
    "resource_type": "نوع منبع",
    "event_type": "نوع رویداد",
    "leave_type": "نوع مرخصی",
    "from_status": "وضعیت مبدأ",
    "to_status": "وضعیت مقصد",
    "from_class_group": "کلاس مبدأ",
    "to_class_group": "کلاس مقصد",
    "source_year": "سال مبدأ",
    "target_year": "سال مقصد",
    "target_grade_level": "پایه مقصد",
    "old_status": "وضعیت پیشین",
    "new_status": "وضعیت جدید",
    # --- علت و توضیح --------------------------------------------------------
    "cancel_reason": "علت لغو",
    "revoke_reason": "علت ابطال",
    "exit_reason": "علت خروج",
    "termination_reason": "علت خاتمه",
    "decision_reason": "علت تصمیم",
    "amended_reason": "علت اصلاح",
    "void_reason": "علت ابطال",
    "reason_code": "کد علت",
    "decision": "تصمیم",
    "decision_note": "توضیح تصمیم",
    "close_note": "توضیح بستن",
    # --- شماره سند ----------------------------------------------------------
    "order_no": "شماره سفارش",
    "invoice_no": "شماره صورتحساب",
    "payment_no": "شماره پرداخت",
    "refund_no": "شماره استرداد",
    "entry_no": "شماره سند",
    "document_no": "شماره سند",
    "receipt_no": "شماره رسید",
    "request_no": "شماره درخواست",
    "contract_no": "شماره قرارداد",
    "ticket_no": "شماره تیکت",
    "serial_no": "شماره سریال",
    "line_no": "شماره سطر",
    "cheque_no": "شماره چک",
    "vendor_invoice_no": "شماره فاکتور تأمین‌کننده",
    "asset_tag": "برچسب اموال",
}

#: قاعده‌های پسوندی برای نام‌هایی که در واژه‌نامه نیستند.
#:
#: هر قاعده «پسوند → الگو» است و `{}` جای برچسبِ باقیمانده نام را می‌گیرد؛
#: باقیمانده خودش از واژه‌نامه خوانده می‌شود. مثلاً `vendor_code` می‌شود
#: «کد تأمین‌کننده». اگر باقیمانده ترجمه نداشته باشد، قاعده اعمال نمی‌شود تا
#: برچسب نیمه‌فارسی تولید نشود.
_SUFFIX_RULES: tuple[tuple[str, str], ...] = (
    ("_by_id", "{} (کاربر)"),
    ("_at", "زمان {}"),
    ("_on", "تاریخ {}"),
    ("_no", "شماره {}"),
    ("_code", "کد {}"),
    ("_id", "شناسه {}"),
    ("_type", "نوع {}"),
    ("_status", "وضعیت {}"),
    ("_reason", "علت {}"),
    ("_note", "توضیح {}"),
    ("_count", "تعداد {}"),
    ("_amount", "مبلغ {}"),
    ("_qty", "مقدار {}"),
    ("_name", "نام {}"),
)


def resolve_label(field_name: str) -> str | None:
    """برچسب فارسی یک نام فیلد، یا `None` اگر واژه‌نامه پوششش نمی‌دهد."""
    direct = FIELD_LABELS.get(field_name)
    if direct:
        return direct

    for suffix, pattern in _SUFFIX_RULES:
        if not field_name.endswith(suffix):
            continue
        stem = FIELD_LABELS.get(field_name[: -len(suffix)])
        if stem:
            return pattern.format(stem)
    return None


def _needs_label(field: models.Field) -> bool:
    """
    آیا فیلد برچسب فارسی صریح دارد؟

    جنگو در نبود `verbose_name`، نام فیلد را با فاصله برمی‌گرداند؛ پس نبودِ
    حرف فارسی نشانه قابل‌اتکایی برای «برچسب داده نشده» است.
    """
    return not _PERSIAN.search(str(getattr(field, "verbose_name", "") or ""))


def apply_field_labels() -> int:
    """
    برچسب‌های واژه‌نامه را روی فیلدهای بدون `verbose_name` می‌نشاند.

    از `CoreConfig.ready()` صدا زده می‌شود — یعنی پس از بارگذاری همه مدل‌ها و
    پیش از ساخته‌شدن اولین فرم، سریالایزر یا Schema. تعداد فیلدهای برچسب‌خورده
    را برمی‌گرداند تا در تست قابل ادعا باشد.
    """
    applied = 0
    for config in django_apps.get_app_configs():
        if not config.name.startswith("apps."):
            continue
        for model in config.get_models():
            for field in model._meta.get_fields():
                if not isinstance(field, models.Field) or field.auto_created:
                    continue
                if not _needs_label(field):
                    continue
                label = resolve_label(field.name)
                if label:
                    field.verbose_name = label
                    applied += 1
    return applied
