"""
واژه‌نامه فارسی فیلدهای مشترک قرارداد OpenAPI.

چرا اینجا و نه در `verbose_name` مدل‌ها؟

بخشی از فیلدهای قرارداد اصلاً فیلد مدل نیستند: خروجی `SerializerMethodField`
(مثل `status_display`)، پاکت صفحه‌بندی (`next`, `previous`, `results`) و بدنه
سریالایزرهای فرمانی. این‌ها `verbose_name` ندارند و برچسب فارسی‌شان جایی جز
اینجا نمی‌نشیند.

`_LABELS` بر اساس *نام* فیلد است، پس یک بار نوشتن، همه Schemaها را پوشش می‌دهد.
نام‌های camelCase پیش از جست‌وجو به snake_case تبدیل می‌شوند.

اولویت: `verbose_name` مدل و `help_text` سریالایزر همیشه مقدم‌اند؛ این واژه‌نامه
فقط جای خالی را پر می‌کند.
"""

from __future__ import annotations

import re

# ---------------------------------------------------------------------------
# برچسب فیلدهای پرتکرار
# ---------------------------------------------------------------------------
_LABELS: dict[str, str] = {
    # --- زیرساخت و ممیزی ---
    "id": "شناسه",
    "version": "نسخه رکورد (برای هدر If-Match)",
    "created_at": "زمان ایجاد",
    "updated_at": "زمان آخرین تغییر",
    "created_by_id": "شناسه کاربر ایجادکننده",
    "updated_by_id": "شناسه کاربر آخرین تغییر",
    "deleted_at": "زمان حذف نرم",
    "delete_reason": "علت حذف",
    "record_status": "وضعیت رکورد",
    "tenant": "سازمان",
    "tenant_id": "شناسه سازمان",
    "correlation_id": "شناسه ردیابی درخواست",
    "client_ip": "نشانی IP کلاینت",
    "user_agent": "شناسه مرورگر کلاینت",
    # --- پاکت صفحه‌بندی ---
    "count": "تعداد کل رکوردها",
    "page": "شماره صفحه جاری",
    "page_size": "اندازه صفحه",
    "page_count": "تعداد صفحات",
    "next": "نشانی صفحه بعد (تهی یعنی آخرین صفحه)",
    "previous": "نشانی صفحه قبل (تهی یعنی اولین صفحه)",
    "results": "رکوردهای این صفحه",
    "rows": "سطرها",
    "lines": "سطرهای سند",
    "items": "اقلام",
    "actions": "اقدامات",
    "details": "جزئیات",
    "options": "گزینه‌ها",
    "media": "رسانه‌های پیوست",
    "steps": "گام‌ها",
    "allocations": "تخصیص‌ها",
    "attendees": "حاضران",
    "guardians": "اولیا",
    "questions": "سؤالات",
    "terms": "ترم‌ها",
    "feedbacks": "بازخوردها",
    # --- عمومی ---
    "title": "عنوان",
    "title_name": "عنوان",
    "code": "کد",
    "parent_code": "کد والد",
    "name": "نام",
    "full_name": "نام کامل",
    "description": "توضیح",
    "note": "یادداشت",
    "notes": "یادداشت‌ها",
    "comment": "توضیح",
    "message": "پیام",
    "error_message": "پیام خطا",
    "reason": "علت",
    "reason_code": "کد علت",
    "content": "محتوا",
    "body": "متن",
    "value": "مقدار",
    "status": "وضعیت",
    "mode": "حالت",
    "method": "روش",
    "action": "عمل",
    "source": "منبع",
    "source_id": "شناسه منبع",
    "source_type": "نوع منبع",
    "direction": "جهت",
    "priority": "اولویت",
    "severity": "شدت",
    "purpose": "هدف",
    "outcome": "نتیجه",
    "difference": "اختلاف",
    "classification": "طبقه‌بندی",
    "visibility": "سطح نمایش",
    "confidentiality_level": "سطح محرمانگی",
    "display_order": "ترتیب نمایش",
    "line_no": "شماره سطر",
    "sequence_no": "شماره ترتیب",
    "version_no": "شماره نسخه",
    "url": "نشانی اینترنتی",
    "language": "زبان",
    "locale": "زبان و محلی‌سازی",
    "preferred_locale": "زبان ترجیحی",
    "timezone": "منطقه زمانی",
    "country": "کشور",
    "latitude": "عرض جغرافیایی",
    "longitude": "طول جغرافیایی",
    "location": "مکان",
    "location_room": "اتاق یا محل استقرار",
    "recurrence": "الگوی تکرار",
    "quantity": "تعداد",
    "item_count": "تعداد اقلام",
    "attachment": "پیوست",
    "file": "فایل",
    "logo": "نشان سازمان",
    "barcode": "بارکد",
    "resolution": "نتیجه رسیدگی",
    "resource_type": "نوع منبع",
    "entity_type": "نوع موجودیت",
    "entity_id": "شناسه موجودیت",
    "entity_label": "برچسب موجودیت",
    "related_type": "نوع موجودیت مرتبط",
    "related_id": "شناسه موجودیت مرتبط",
    "owner_type": "نوع مالک",
    "owner_id": "شناسه مالک",
    "subject": "موضوع",
    "subject_id": "شناسه موضوع",
    "subject_type": "نوع موضوع",
    "subject_label": "برچسب موضوع",
    "subject_template": "قالب موضوع پیام",
    "instructions": "دستورالعمل",
    "justification": "توجیه درخواست",
    "evidence_ref": "ارجاع مستند",
    "evidence_file": "فایل مستند",
    "scope_note": "توضیح دامنه",
    # --- زمان و تاریخ ---
    "occurred_at": "زمان رخداد",
    "starts_at": "زمان شروع",
    "ends_at": "زمان پایان",
    "starts_on": "تاریخ شروع",
    "ends_on": "تاریخ پایان",
    "due_at": "مهلت",
    "due_on": "سررسید",
    "expires_at": "زمان انقضا",
    "expiry_date": "تاریخ انقضا",
    "valid_until": "معتبر تا",
    "effective_from": "معتبر از",
    "effective_to": "معتبر تا",
    "effective_until": "معتبر تا",
    "period_start": "شروع دوره",
    "period_end": "پایان دوره",
    "period_from": "از دوره",
    "period_to": "تا دوره",
    "entry_date": "تاریخ ثبت",
    "work_date": "تاریخ کاری",
    "run_date": "تاریخ سرویس",
    "session_date": "تاریخ جلسه",
    "issued_on": "تاریخ صدور",
    "opened_at": "زمان گشایش",
    "opened_on": "تاریخ گشایش",
    "closed_at": "زمان اختتام",
    "closed_on": "تاریخ اختتام",
    "close_note": "یادداشت اختتام",
    "submitted_at": "زمان ثبت",
    "requested_at": "زمان درخواست",
    "approved_at": "زمان تأیید",
    "decided_at": "زمان تصمیم",
    "reviewed_at": "زمان بازبینی",
    "resolved_at": "زمان رسیدگی",
    "completed_at": "زمان تکمیل",
    "published_at": "زمان انتشار",
    "revoked_at": "زمان ابطال",
    "verified_at": "زمان تأیید هویت",
    "returned_at": "زمان بازگشت",
    "received_at": "زمان دریافت",
    "assigned_at": "زمان تخصیص",
    "changed_at": "زمان تغییر",
    "calculated_at": "زمان محاسبه",
    "scanned_at": "زمان اسکن",
    "saved_at": "زمان ذخیره",
    "loaned_at": "زمان امانت",
    "departed_at": "زمان حرکت",
    "scheduled_at": "زمان زمان‌بندی‌شده",
    "scheduled_time": "ساعت برنامه",
    "reconciled_at": "زمان مغایرت‌گیری",
    "next_followup_at": "زمان پیگیری بعدی",
    "held_at": "زمان برگزاری",
    "planned_for": "برنامه‌ریزی‌شده برای",
    "needed_by": "مورد نیاز تا",
    "check_in_at": "زمان ورود",
    "check_out_at": "زمان خروج",
    "quiet_hours_start": "شروع ساعات سکوت",
    "quiet_hours_end": "پایان ساعات سکوت",
    "duration_minutes": "مدت (دقیقه)",
    "worked_minutes": "دقایق کارکرد",
    "overtime_minutes": "دقایق اضافه‌کار",
    "weekly_minutes": "دقایق هفتگی",
    "late_minutes": "دقایق تأخیر",
    "early_leave_minutes": "دقایق خروج زودهنگام",
    "requested_minutes": "دقایق درخواستی",
    "time_limit_minutes": "محدودیت زمانی (دقیقه)",
    "time_spent_seconds": "زمان صرف‌شده (ثانیه)",
    "remaining_seconds": "ثانیه‌های باقی‌مانده",
    "useful_life_months": "عمر مفید (ماه)",
    # --- هویت و دسترسی ---
    "username": "نام کاربری",
    "password": "گذرواژه",
    "must_change_password": "تغییر اجباری گذرواژه در ورود بعدی",
    "refresh": "توکن تازه‌سازی",
    "access": "توکن دسترسی",
    "email": "رایانامه",
    "phone": "تلفن",
    "national_id": "کد ملی",
    "mfa_method": "روش احراز هویت دومرحله‌ای",
    "mfa_enabled": "احراز هویت دومرحله‌ای فعال است",
    "actor_user_id": "شناسه کاربر عامل",
    "actor_username": "نام کاربری عامل",
    "grant_reason": "علت اعطای دسترسی",
    "revoke_reason": "علت ابطال دسترسی",
    "review_type": "نوع بازبینی دسترسی",
    "reviewer_id": "شناسه بازبین",
    "person_detail": "مشخصات شخص",
    "address_line": "نشانی",
    "address_type": "نوع نشانی",
    "document_type": "نوع مدرک",
    "contact_person": "شخص رابط",
    "emergency_contact": "تماس اضطراری",
    "emergency_contact_name": "نام تماس اضطراری",
    "emergency_contact_phone": "تلفن تماس اضطراری",
    # --- ساختار آموزشی ---
    "school_name": "نام مدرسه",
    "campus_name": "نام شعبه",
    "grade_level": "پایه تحصیلی",
    "grade_level_title": "عنوان پایه تحصیلی",
    "class_group_id": "شناسه کلاس",
    "class_group_code": "کد کلاس",
    "course_title": "عنوان درس",
    "term": "ترم",
    "term_title": "عنوان ترم",
    "program_title": "عنوان دوره تحصیلی",
    "room_code": "کد اتاق",
    "room_type": "نوع فضا",
    "occupied_seats": "صندلی‌های اشغال‌شده",
    "available_seats": "صندلی‌های خالی",
    "seat_no": "شماره صندلی",
    "drop_policy": "قاعده حذف درس",
    # --- دانش‌آموز و ولی ---
    "student_id": "شناسه دانش‌آموز",
    "student_no": "شماره دانش‌آموزی",
    "student_name": "نام دانش‌آموز",
    "applicant_name": "نام متقاضی",
    "guardian_name": "نام ولی",
    "guardian_notified_at": "زمان اطلاع به ولی",
    "submitted_by_guardian_id": "شناسه ولی ثبت‌کننده",
    "enrollment": "ثبت‌نام",
    "enrollment_id": "شناسه ثبت‌نام",
    "registration_status": "وضعیت ثبت‌نام",
    "exit_reason": "علت خروج",
    # --- منابع انسانی ---
    "employee_name": "نام کارمند",
    "teacher_name": "نام معلم",
    "contract_no": "شماره قرارداد",
    "contract_type": "نوع قرارداد",
    "termination_reason": "علت خاتمه قرارداد",
    "position_type": "نوع سمت",
    "qualification_status": "وضعیت صلاحیت",
    "specialization": "تخصص",
    "responsibility": "شرح مسئولیت",
    "duty": "وظیفه",
    "leave_type": "نوع مرخصی",
    "counselor_employee_id": "شناسه مشاور",
    "proctor_employee_id": "شناسه مراقب آزمون",
    "driver_employee_id": "شناسه راننده",
    "default_driver_employee_id": "شناسه راننده پیش‌فرض",
    "supervisor_employee_id": "شناسه سرپرست",
    "keeper_employee_id": "شناسه انباردار",
    "assignee_user_id": "شناسه کاربر مسئول",
    "approver_user_id": "شناسه کاربر تأییدکننده",
    "approver_role_code": "کد نقش تأییدکننده",
    "requested_by_id": "شناسه کاربر درخواست‌دهنده",
    "submitted_by_id": "شناسه کاربر ثبت‌کننده",
    "reviewed_by_id": "شناسه کاربر بازبین",
    # --- آموزش و حضور ---
    "session_type": "نوع جلسه",
    "session_id": "شناسه جلسه",
    "attendance_status": "وضعیت حضور",
    "attendance_summary": "خلاصه حضور و غیاب",
    "finalization_status": "وضعیت قطعی‌سازی",
    "finalized_sessions": "جلسات قطعی‌شده",
    "pending_sessions": "جلسات در انتظار قطعی‌سازی",
    "total_sessions": "تعداد کل جلسات",
    "absent_today": "تعداد غایبان امروز",
    "has_justification": "دارای توجیه است",
    "assignment_title": "عنوان تکلیف",
    "assignment_detail": "جزئیات تکلیف",
    "submission_stats": "آمار تحویل تکلیف",
    "is_late": "با تأخیر تحویل شده است",
    "feedback": "بازخورد",
    "teacher_comment": "نظر معلم",
    "principal_comment": "نظر مدیر",
    # --- آزمون ---
    "exam_title": "عنوان آزمون",
    "exam_question_id": "شناسه سؤال آزمون",
    "question_type": "نوع سؤال",
    "question_body": "متن سؤال",
    "question_count": "تعداد سؤالات",
    "section_title": "عنوان بخش",
    "section_count": "تعداد بخش‌ها",
    "difficulty": "سطح دشواری",
    "is_correct": "گزینه صحیح است",
    "max_score": "نمره کل",
    "total_question_score": "مجموع بارم سؤالات",
    "awarded_score": "نمره اعطاشده",
    "attempt_id": "شناسه تلاش",
    "attempt_no": "شماره تلاش",
    "attempt_limit": "سقف تعداد تلاش",
    "max_attempts": "حداکثر تعداد تلاش",
    "allow_backtrack": "اجازه بازگشت به سؤال قبلی",
    "show_result_immediately": "نمایش فوری نتیجه به دانش‌آموز",
    "appeal_deadline": "مهلت اعتراض",
    "grading_status": "وضعیت تصحیح",
    "results_published_at": "زمان انتشار نتایج",
    "save_revision": "شماره ویرایش ذخیره پاسخ",
    "saved_answer": "پاسخ ذخیره‌شده",
    "investigation_note": "یادداشت بررسی تخلف",
    # --- نمره و کارنامه ---
    "score": "نمره",
    "final_score": "نمره نهایی",
    "letter_grade": "نمره حرفی",
    "qualitative_level": "سطح کیفی",
    "result_status": "وضعیت نتیجه",
    "category_title": "عنوان دسته ارزشیابی",
    "item_title": "عنوان قلم",
    "calculation_version": "نسخه فرمول محاسبه",
    "is_final": "نهایی است",
    "is_editable": "قابل ویرایش است",
    "amended_reason": "علت اصلاح",
    # --- مالی ---
    "amount": "مبلغ (ریال)",
    "total_amount": "مبلغ کل (ریال)",
    "unit_amount": "مبلغ واحد (ریال)",
    "unit_price": "قیمت واحد (ریال)",
    "unit_cost": "بهای واحد (ریال)",
    "cost_amount": "مبلغ هزینه (ریال)",
    "tax_amount": "مبلغ مالیات (ریال)",
    "discount_amount": "مبلغ تخفیف (ریال)",
    "discount_type": "نوع تخفیف",
    "estimated_amount": "مبلغ برآوردی (ریال)",
    "estimated_unit_price": "قیمت واحد برآوردی (ریال)",
    "budget_reserved_amount": "مبلغ رزروشده بودجه (ریال)",
    "acquisition_cost": "بهای تمام‌شده تملک (ریال)",
    "monthly_fee": "هزینه ماهانه (ریال)",
    "currency": "واحد پول (ISO 4217)",
    "decimal_places": "تعداد رقم اعشار واحد پول",
    "balance": "مانده",
    "opening_balance": "مانده ابتدای دوره",
    "closing_balance": "مانده پایان دوره",
    "debit": "بدهکار",
    "credit": "بستانکار",
    "account_code": "کد حساب",
    "account_title": "عنوان حساب",
    "account_type": "نوع حساب",
    "expense_account_id": "شناسه حساب هزینه",
    "cost_center_id": "شناسه مرکز هزینه",
    "invoice": "صورتحساب",
    "invoice_no": "شماره صورتحساب",
    "payment_no": "شماره پرداخت",
    "fee_type": "نوع تعرفه",
    "installment_count": "تعداد اقساط",
    "bank_name": "نام بانک",
    "bank_account_title": "عنوان حساب بانکی",
    "cheque_no": "شماره چک",
    "cheque_due_date": "سررسید چک",
    "gateway_reference": "کد پیگیری درگاه پرداخت",
    "fine_paid": "جریمه پرداخت‌شده",
    # --- خرید و انبار ---
    "vendor_name": "نام تأمین‌کننده",
    "vendor_invoice_no": "شماره فاکتور فروشنده",
    "vendor_invoice_amount": "مبلغ فاکتور فروشنده (ریال)",
    "order_no": "شماره سفارش",
    "ordered_qty": "مقدار سفارش",
    "ordered_on": "تاریخ سفارش",
    "expected_on": "تاریخ تحویل مورد انتظار",
    "item_sku": "کد کالا (SKU)",
    "item_type": "نوع قلم",
    "warehouse": "انبار",
    "warehouse_code": "کد انبار",
    "min_stock": "حداقل موجودی",
    "max_stock": "حداکثر موجودی",
    "lot_no": "شماره بچ",
    "serial_no": "شماره سریال",
    "quality_status": "وضعیت کیفی",
    "condition_status": "وضعیت فیزیکی",
    "condition_on_assign": "وضعیت هنگام تحویل",
    "condition_on_return": "وضعیت هنگام بازگشت",
    "asset_tag": "پلاک اموال",
    "lifecycle_status": "وضعیت چرخه عمر",
    "accumulated_depreciation": "استهلاک انباشته (ریال)",
    "book_value": "ارزش دفتری (ریال)",
    "acquired_on": "تاریخ تملک",
    "warranty_until": "پایان گارانتی",
    "insurance_no": "شماره بیمه",
    "insurance_policy_no": "شماره بیمه‌نامه",
    "insurance_valid_until": "اعتبار بیمه تا",
    "maintenance_type": "نوع تعمیر و نگهداری",
    "model_name": "نام مدل",
    "assignee_type": "نوع تحویل‌گیرنده",
    "assignee_id": "شناسه تحویل‌گیرنده",
    "current_assignee": "تحویل‌گیرنده فعلی",
    # --- خدمات دانش‌آموزی ---
    "blood_type": "گروه خونی",
    "height_cm": "قد (سانتی‌متر)",
    "weight_kg": "وزن (کیلوگرم)",
    "family_physician": "پزشک خانواده",
    "incident_type": "نوع رخداد انضباطی",
    "action_taken": "اقدام انجام‌شده",
    "action_type": "نوع اقدام",
    "referral_source": "منبع ارجاع",
    "alert_type": "نوع هشدار",
    "event_type": "نوع رخداد",
    "cancel_reason": "علت لغو",
    "decision": "تصمیم",
    "decision_note": "توضیح تصمیم",
    "decision_reason": "علت تصمیم",
    "approval_status": "وضعیت تأیید",
    "isbn": "شابک",
    "author": "پدیدآور",
    "publisher": "ناشر",
    "publish_year": "سال انتشار",
    "material_type": "نوع منبع کتابخانه",
    "is_available": "در دسترس است",
    "route_code": "کد مسیر",
    "vehicle_plate": "پلاک خودرو",
    # --- گردش کار و فایل ---
    "workflow_code": "کد گردش کار",
    "workflow_version": "نسخه گردش کار",
    "current_step": "گام جاری",
    "channel": "کانال ارسال",
    "allow_sms": "اجازه ارسال پیامک",
    "allow_email": "اجازه ارسال رایانامه",
    "allow_push": "اجازه اعلان درون‌برنامه‌ای",
    "allow_promotional": "اجازه دریافت پیام تبلیغاتی",
    "original_name": "نام اصلی فایل",
    "media_type": "نوع محتوا (MIME)",
    "size_bytes": "حجم فایل (بایت)",
    "sha256": "درهم‌ساز SHA-256 فایل",
    "scan_status": "وضعیت اسکن بدافزار",
    "is_required": "الزامی است",
    "is_mandatory": "اجباری است",
    "is_active": "فعال است",
    # --- نام موجودیت‌ها ---
    # کلیدهای خارجی با همین نام‌ها می‌آیند (`category`, `enrollment`, …) و
    # قواعد پسوندی هم ریشه خود را از اینجا برمی‌دارند (`category_title`).
    "person": "شخص",
    "user": "کاربر",
    "role": "نقش",
    "permission": "مجوز",
    "school": "مدرسه",
    "campus": "شعبه",
    "academic_year": "سال تحصیلی",
    "program": "دوره تحصیلی",
    "subject_area": "حوزه درسی",
    "course": "درس",
    "course_offering": "ارائه درس",
    "class_group": "کلاس",
    "student": "دانش‌آموز",
    "guardian": "ولی",
    "applicant": "متقاضی",
    "application": "پرونده پذیرش",
    "employee": "کارمند",
    "contract": "قرارداد",
    "session": "جلسه",
    "assignment": "تکلیف",
    "submission": "تحویل تکلیف",
    "exam": "آزمون",
    "question": "سؤال",
    "bank": "بانک سؤال",
    "attempt": "تلاش آزمون",
    "exam_question": "سؤال آزمون",
    "category": "دسته",
    "grade_item": "قلم نمره",
    "report_card": "کارنامه",
    "fee": "تعرفه",
    "payment": "پرداخت",
    "refund": "استرداد",
    "account": "حساب",
    "journal_entry": "سند حسابداری",
    "supplier": "تأمین‌کننده",
    "vendor": "تأمین‌کننده",
    "purchase_order": "سفارش خرید",
    "item": "کالا",
    "asset": "دارایی",
    "stock_movement": "حرکت موجودی",
    "book": "کتاب",
    "loan": "امانت",
    "route": "مسیر",
    "vehicle": "خودرو",
    "workflow": "گردش کار",
    "notification": "اعلان",
    "template": "قالب",
    # --- فیلدهای نماهای گزارشی و بدنه‌های فرمانی ---
    "success": "عملیات موفق بود",
    "affected": "تعداد رکوردهای متأثر",
    "errors": "خطاها",
    "field_errors": "خطاهای فیلدی",
    "valid_rows": "سطرهای معتبر",
    "invalid_rows": "سطرهای نامعتبر",
    "columns": "ستون‌ها",
    "categories": "دسته‌ها",
    "sections": "بخش‌ها",
    "sessions": "جلسات",
    "entries": "ردیف‌ها",
    "stops": "ایستگاه‌ها",
    "messages": "پیام‌ها",
    "attempts": "تلاش‌های ارسال",
    "students": "دانش‌آموزان",
    "teachers": "معلمان",
    "offerings": "ارائه‌های درس",
    "enrollments": "ثبت‌نام‌ها",
    "consents": "رضایت‌نامه‌ها",
    "contracts": "قراردادها",
    "assignments": "انتساب‌ها",
    "qualifications": "صلاحیت‌ها",
    "discounts": "تخفیف‌ها",
    "alerts": "هشدارها",
    "roles": "نقش‌ها",
    "permissions": "مجوزها",
    "contexts": "Contextهای کاری در دسترس",
    "role_assignments": "انتساب‌های نقش",
    "class_memberships": "عضویت‌های کلاسی",
    "contact_points": "راه‌های تماس",
    "addresses": "نشانی‌ها",
    "tag_ids": "شناسه برچسب‌ها",
    "subtitle": "زیرعنوان",
    "payload": "بار داده رخداد",
    "response_payload": "بار پاسخ دانش‌آموز",
    "correct_answer": "کلید پاسخ",
    "grading_rubric": "راهنمای تصحیح",
    "explanation": "پاسخ تشریحی",
    "response_text": "متن پاسخ",
    "default_score": "بارم پیش‌فرض",
    "auto_score": "نمره تصحیح خودکار",
    "manual_score": "نمره تصحیح دستی",
    "raw_score": "نمره خام",
    "new_score": "نمره جدید",
    "old_score": "نمره قبلی",
    "score_before": "نمره پیش از رسیدگی",
    "score_after": "نمره پس از رسیدگی",
    "displayed_score": "نمره نمایشی کارنامه",
    "displayed_level": "سطح کیفی نمایشی کارنامه",
    "average_score": "میانگین نمره",
    "category_averages": "میانگین هر دسته",
    "correct_percent": "درصد پاسخ صحیح",
    "response_count": "تعداد پاسخ‌ها",
    "average_time_seconds": "میانگین زمان پاسخ (ثانیه)",
    "weight": "وزن",
    "recorded_count": "تعداد نمرات ثبت‌شده",
    "registration_count": "تعداد ثبت‌نام‌شدگان",
    "locked_at": "زمان قفل شدن",
    "started_at": "زمان شروع",
    "last_saved_at": "زمان آخرین ذخیره",
    "attempted_at": "زمان تلاش",
    "recorded_at": "زمان ثبت",
    "generated_at": "زمان تولید",
    "executed_at": "زمان اجرا",
    "confirmed_at": "زمان تأیید",
    "posted_at": "زمان ثبت سند",
    "allocated_at": "زمان تخصیص",
    "attendance_finalized_at": "زمان قطعی‌سازی حضور و غیاب",
    "date_joined": "تاریخ عضویت",
    "last_login_at": "زمان آخرین ورود",
    "sent_at": "زمان ارسال",
    "read_at": "زمان مطالعه",
    "last_event_at": "زمان آخرین رخداد",
    "last_event": "آخرین رخداد",
    "event_count": "تعداد رخدادها",
    "enrolled_on": "تاریخ ثبت‌نام",
    "exit_date": "تاریخ خروج",
    "effective_on": "تاریخ اعمال",
    "first_due_date": "سررسید قسط اول",
    "interval_days": "فاصله اقساط (روز)",
    "loan_days": "مدت امانت (روز)",
    "renewal_count": "تعداد تمدید",
    "is_overdue": "دیرکرد دارد",
    "is_open": "باز است",
    "is_balanced": "سند تراز است",
    "is_teacher": "معلم است",
    "is_auto_graded": "تصحیح خودکار دارد",
    "is_currently_effective": "هم‌اکنون معتبر است",
    "is_locked": "قفل است",
    "has_user_account": "حساب کاربری دارد",
    "below_threshold": "زیر آستانه هشدار",
    "below_reorder_point": "زیر نقطه سفارش",
    "matched": "تطبیق برقرار است",
    "applied": "اعمال شد",
    "sent": "ارسال شد",
    "mfa_required": "احراز هویت دومرحله‌ای لازم است",
    "is_superuser": "کاربر ارشد سامانه",
    "display_name": "نام نمایشی",
    "mobile": "تلفن همراه",
    "new_password": "گذرواژه جدید",
    "author_user_id": "شناسه کاربر نویسنده",
    "changed_by_id": "شناسه کاربر تغییردهنده",
    "requester_user_id": "شناسه کاربر درخواست‌دهنده",
    "requester_name": "نام درخواست‌دهنده",
    "recipient_name": "نام گیرنده",
    "recipient_count": "تعداد گیرندگان",
    "sample_message": "نمونه پیام تولیدشده",
    "audience": "مخاطبان",
    "payer_name": "نام پرداخت‌کننده",
    "borrower_name": "نام امانت‌گیرنده",
    "borrower_person": "شناسه شخص امانت‌گیرنده",
    "substitute_name": "نام جانشین",
    "guardian_mobile": "تلفن همراه ولی",
    "responsible_guardian_name": "نام ولی مسئول پرداخت",
    "gender": "جنسیت",
    "relationship": "نسبت",
    "consent_type": "نوع رضایت‌نامه",
    "contact_type": "نوع راه تماس",
    "school_type": "نوع مدرسه",
    "assessment_scheme": "نظام ارزشیابی",
    "weekday": "روز هفته",
    "transfer_type": "نوع جابه‌جایی",
    "verification_status": "وضعیت احراز",
    "review_status": "وضعیت بازبینی",
    "from_status": "وضعیت قبلی",
    "to_status": "وضعیت جدید",
    "new_status": "وضعیت جدید",
    "old_status": "وضعیت قبلی",
    "from_class_code": "کد کلاس مبدأ",
    "to_class_code": "کد کلاس مقصد",
    "current_class": "کلاس فعلی",
    "current_class_code": "کد کلاس فعلی",
    "current_grade": "پایه فعلی",
    "home_room_code": "کد کلاس‌درس ثابت",
    "target_grade": "پایه مقصد",
    "target_grade_level_id": "شناسه پایه مقصد",
    "suggested_decision": "تصمیم پیشنهادی سامانه",
    "conflicting_entry_id": "شناسه ردیف متعارض",
    "position_title": "عنوان سمت",
    "primary_position": "سمت اصلی",
    "org_unit_title": "عنوان واحد سازمانی",
    "fee_plan_title": "عنوان طرح شهریه",
    "uom_title": "عنوان واحد شمارش",
    "cost_center": "مرکز هزینه",
    "cost_center_title": "عنوان مرکز هزینه",
    "fiscal_year": "سال مالی",
    "entry_no": "شماره سند",
    "document_no": "شماره سند انبار",
    "receipt_no": "شماره رسید",
    "request_no": "شماره درخواست",
    "ticket_no": "شماره تیکت",
    "net_amount": "مبلغ خالص (ریال)",
    "allocated_amount": "مبلغ تخصیص‌یافته (ریال)",
    "unallocated_amount": "مبلغ تخصیص‌نیافته (ریال)",
    "total_invoiced": "جمع صورتحساب‌ها (ریال)",
    "total_paid": "جمع پرداختی‌ها (ریال)",
    "order_amount": "مبلغ سفارش (ریال)",
    "received_value": "ارزش کالای دریافتی (ریال)",
    "tolerance": "تلورانس مجاز",
    "void_reason": "علت ابطال",
    "signed_quantity": "مقدار علامت‌دار (ورود مثبت، خروج منفی)",
    "available_qty": "موجودی قابل‌دسترس",
    "received_qty": "مقدار دریافت‌شده",
    "remaining_qty": "مقدار باقی‌مانده",
    "total_on_hand": "موجودی کل",
    "order_line": "شناسه سطر سفارش",
    "sku": "کد کالا (SKU)",
    "copy": "شناسه نسخه",
    "copy_barcode": "بارکد نسخه",
    "copy_count": "تعداد نسخه‌ها",
    "available_count": "تعداد نسخه در دسترس",
    "active_alert_count": "تعداد هشدارهای فعال",
    "active_rider_count": "تعداد مسافران فعال",
    "rider_count": "تعداد مسافران",
    "capacity": "ظرفیت",
    "vehicle_capacity": "ظرفیت خودرو",
    "pickup_stop": "ایستگاه سوارشدن",
    "pickup_stop_title": "عنوان ایستگاه سوارشدن",
    "dropoff_stop": "ایستگاه پیاده‌شدن",
    "route_run_id": "شناسه سرویس",
    "payslip_count": "تعداد فیش حقوقی",
    "incident_count": "تعداد رخدادهای انضباطی",
    "commendation_count": "تعداد تشویق‌ها",
    "total_points": "جمع امتیاز",
    "by_severity": "تفکیک بر اساس شدت",
    "by_status": "تفکیک بر اساس وضعیت",
    "present_percent": "درصد حضور",
    "consecutive_absences": "غیبت‌های پیاپی",
    "academic_summary": "خلاصه آموزشی",
    "financial_summary": "خلاصه مالی",
    "health_summary": "خلاصه سلامت",
    "assigned_weekly_minutes": "دقایق هفتگی تخصیص‌یافته",
    "required_weekly_minutes": "دقایق هفتگی موظفی",
    "remaining_minutes": "دقایق باقی‌مانده",
    "teacher_profile_id": "شناسه پرونده معلم",
    "provider": "ارائه‌دهنده سرویس ارسال",
    "provider_reference": "کد پیگیری ارائه‌دهنده",
    "result": "نتیجه",
    "retry_count": "تعداد تلاش مجدد",
    "last_error": "آخرین خطا",
    "aggregate_type": "نوع Aggregate",
    "aggregate_id": "شناسه Aggregate",
    "schema_version": "نسخه قالب رخداد",
    "integration_code": "کد سامانه طرف مقابل",
    "external_message_id": "شناسه پیام در سامانه بیرونی",
    "received_or_sent_at": "زمان دریافت یا ارسال",
    "scope_type": "نوع دامنه دسترسی",
    "scope_id": "شناسه دامنه دسترسی",
    "address_detail": "مشخصات نشانی",
    "current_version_detail": "مشخصات نسخه جاری",
    "attempt_answer_id": "شناسه پاسخ تلاش",
}

# ---------------------------------------------------------------------------
# قواعد پسوندی برای دنباله بلند نام‌ها (آنچه در واژه‌نامه بالا نیامده)
# ---------------------------------------------------------------------------
_SUFFIX_RULES: tuple[tuple[str, str], ...] = (
    ("_display", "برچسب فارسی {stem}"),
    ("_by_id", "شناسه کاربر {stem}"),
    ("_employee_id", "شناسه کارمند {stem}"),
    ("_count", "تعداد {stem}"),
    ("_minutes", "{stem} (دقیقه)"),
    ("_seconds", "{stem} (ثانیه)"),
    ("_months", "{stem} (ماه)"),
    ("_amount", "مبلغ {stem} (ریال)"),
    ("_qty", "مقدار {stem}"),
    ("_no", "شماره {stem}"),
    ("_code", "کد {stem}"),
    ("_title", "عنوان {stem}"),
    ("_name", "نام {stem}"),
    ("_type", "نوع {stem}"),
    ("_status", "وضعیت {stem}"),
    ("_reason", "علت {stem}"),
    ("_note", "یادداشت {stem}"),
    ("_id", "شناسه {stem}"),
    ("_at", "زمان {stem}"),
    ("_on", "تاریخ {stem}"),
    ("_date", "تاریخ {stem}"),
)

_PREFIX_RULES: tuple[tuple[str, str], ...] = (
    ("is_", "{stem}"),
    ("has_", "دارای {stem}"),
    ("allow_", "اجازه {stem}"),
    ("total_", "مجموع {stem}"),
    ("current_", "{stem} جاری"),
)

_CAMEL_BOUNDARY = re.compile(r"(?<!^)(?=[A-Z])")


def to_snake(name: str) -> str:
    """`classGroupCode` به `class_group_code` تبدیل می‌شود."""
    return _CAMEL_BOUNDARY.sub("_", name).lower()


def label_for(name: str) -> str | None:
    """
    برچسب فارسی یک فیلد، یا `None` اگر شناخته‌شده نباشد.

    ترتیب تلاش: نام دقیق، سپس قاعده پسوندی و پیشوندی روی ریشه شناخته‌شده.
    """
    key = to_snake(name)
    if key in _LABELS:
        return _LABELS[key]

    for suffix, template in _SUFFIX_RULES:
        if not key.endswith(suffix) or len(key) <= len(suffix):
            continue
        stem_label = _LABELS.get(key[: -len(suffix)])
        if stem_label:
            return template.format(stem=stem_label)

    for prefix, template in _PREFIX_RULES:
        if not key.startswith(prefix) or len(key) <= len(prefix):
            continue
        stem_label = _LABELS.get(key[len(prefix) :])
        if stem_label:
            return template.format(stem=stem_label)

    return None
