# Generated by Django 5.2.17 on 2026-08-26 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('gradebook', '0001_initial'),
        ('organization', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseresult',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='courseresult',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='gradeitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_items', to='gradebook.assessmentcategory'),
        ),
        migrations.AddField(
            model_name='gradeitem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='organization.term'),
        ),
        migrations.AddField(
            model_name='reportcarditem',
            name='course_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_card_items', to='gradebook.courseresult'),
        ),
        migrations.AddField(
            model_name='reportcarditem',
            name='report_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gradebook.reportcard'),
        ),
        migrations.AddField(
            model_name='reportcarditem',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='scorechange',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='students.enrollment'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='grade_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='gradebook.gradeitem'),
        ),
        migrations.AddField(
            model_name='studentscore',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_set', to='core.tenant', verbose_name='سازمان'),
        ),
        migrations.AddField(
            model_name='scorechange',
            name='student_score',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='gradebook.studentscore'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcategory',
            constraint=models.UniqueConstraint(fields=('course_offering', 'title'), name='uq_category_offering_title'),
        ),
        migrations.AddIndex(
            model_name='courseresult',
            index=models.Index(fields=['enrollment', 'result_status'], name='gradebook_c_enrollm_04591b_idx'),
        ),
        migrations.AddConstraint(
            model_name='courseresult',
            constraint=models.UniqueConstraint(fields=('course_offering', 'enrollment'), name='uq_result_offering_enrollment'),
        ),
        migrations.AddIndex(
            model_name='gradeitem',
            index=models.Index(fields=['category', 'status'], name='gradebook_g_categor_3e29dd_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('enrollment', 'term', 'version_no'), name='uq_report_card_version'),
        ),
        migrations.AddConstraint(
            model_name='reportcarditem',
            constraint=models.UniqueConstraint(fields=('report_card', 'course_result'), name='uq_report_card_item'),
        ),
        migrations.AddIndex(
            model_name='studentscore',
            index=models.Index(fields=['enrollment', 'status'], name='gradebook_s_enrollm_8f1dfb_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentscore',
            constraint=models.UniqueConstraint(fields=('grade_item', 'enrollment'), name='uq_score_item_enrollment'),
        ),
    ]
